// 中文分片：cn-font-split (Node API) —— 管线第 3 步
// collect_chars.py → subset_fonts.py → 【本脚本】
//
// 输入 : ./subset-ttf/*.otf   （subset_fonts.py 产出的字符集子集）
// 输出 : <站点>/assets/fonts/split/<weight>/*.woff2 + <站点>/assets/css/cjk.css
//
// 每字重切出若干 unicode-range 分片；浏览器按页面实际渲染的码位只拉命中的片。
// cn-font-split 的 result.css 在此被后处理成一份共享 cjk.css：
//   - font-family 统一为 JOBS 里声明的族名
//   - font-weight 改写为真实字重
//   - url("./x.woff2") → 站内相对路径
//   - 删 src:local(...)（防命中本机不一致字体）—— 正则只吞 local(...)，别把 src: 一起吞掉
//   - reporter/demo 产物（index.html / reporter.bin / index.proto / result.css）删除
//
// ⚠ 已知的坑：
//   1. 不要设 chunkSize —— 小值（<~100）在小子集上触发分包死循环（进程挂起被 SIGKILL）；
//      默认值产出 ~28 字形/片，正是想要的粒度。
//   2. 输入必须是 OTF/TTF（subset_fonts.py 已保证）。
//
// 依赖：npm i cn-font-split   （在 tools/ 下 npm install 或全局装均可）
const { fontSplit } = require('cn-font-split');
const fs = require('fs');
const path = require('path');

const HERE = __dirname;

// ===== 按你的站点改这三项 =====
const SITE = path.join(HERE, '..');                          // 站点根目录
const FONTS = path.join(SITE, 'assets', 'fonts', 'split');   // 分片输出目录
const CSS = path.join(SITE, 'assets', 'css', 'cjk.css');     // 生成的 CSS 清单

// ===== JOBS：与 subset_fonts.py 的 JOBS 一一对应 =====
// [子集文件, 输出目录名, CSS font-family, CSS font-weight]
const JOBS = [
  ['sc-45.otf', 'sc-45', 'CJK-SC', 300],
  ['sc-55.otf', 'sc-55', 'CJK-SC', 400],
  ['tc-45.otf', 'tc-45', 'CJK-TC', 300],
  ['tc-55.otf', 'tc-55', 'CJK-TC', 400],
];

function transform(css, dir, family, weight) {
  return css
    // 只保留 @font-face 规则，丢弃元数据头
    .match(/@font-face\{[^}]*\}/g).join('\n')
    .replace(/font-family:"[^"]*"/g, `font-family:'${family}'`)
    .replace(/src:local\("[^"]*"\),/g, 'src:')          // 只删 local(...)，保留 src:
    .replace(/font-weight:\d+/g, `font-weight:${weight}`)
    .replace(/url\("\.\/([^"]+)"\)/g, `url("../fonts/split/${dir}/$1")`);
}

(async () => {
  const parts = [
    '/* Auto-generated by split_cjk.js (cn-font-split) — DO NOT EDIT.\n'
    + ' * CJK font split into unicode-range chunks; browsers fetch only\n'
    + ' * the slices a page actually renders. Regenerate via:\n'
    + ' *   python3 collect_chars.py && python3 subset_fonts.py && node split_cjk.js */\n',
  ];
  for (const [file, dir, family, weight] of JOBS) {
    const out = path.join(FONTS, dir);
    fs.rmSync(out, { recursive: true, force: true });
    console.log('splitting', dir, '...');
    await fontSplit({
      input: path.join(HERE, 'subset-ttf', file),
      outDir: out,
      // NB: 不要设 chunkSize —— 见头部注释
    });
    const raw = fs.readFileSync(path.join(out, 'result.css'), 'utf8');
    const rules = transform(raw, dir, family, weight);
    const n = (rules.match(/@font-face/g) || []).length;
    // 删 reporter/demo 文件，只留 woff2 分片
    for (const junk of ['index.html', 'index.proto', 'reporter.bin', 'result.css'])
      fs.rmSync(path.join(out, junk), { force: true });
    parts.push(`/* ${dir} — ${n} chunks */\n${rules}\n`);
    console.log('  ->', n, 'chunks');
  }
  fs.writeFileSync(CSS, parts.join('\n'));
  console.log('wrote', CSS);
})().catch(e => { console.error(e); process.exit(1); });
